import { StyleSheet } from "react-native";
import { ui } from "../config/designSystem";

const foodMenuStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ui.colors.background,
  },
  searchInputContainer: {
    paddingHorizontal: ui.spacing.md,
    paddingTop: ui.spacing.xs,
    paddingBottom: ui.spacing.xs,
  },
  topActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  loadingIndicator: {
    marginTop: 20,
  },
  promptCompact: {
    marginHorizontal: ui.spacing.md,
    marginBottom: ui.spacing.sm,
    borderRadius: ui.radius.md,
    borderWidth: 1,
    borderColor: "#CDEEEE",
    backgroundColor: "#F3FCFB",
    paddingHorizontal: ui.spacing.sm,
    paddingVertical: 10,
  },
  promptCompactHeader: {
    marginBottom: 6,
  },
  promptCompactTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  promptCompactTitle: {
    fontSize: ui.type.caption,
    color: "#0F766E",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  promptCompactMeta: {
    marginTop: 2,
    fontSize: 12,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  aiPicksStrip: {
    marginHorizontal: ui.spacing.md,
    marginBottom: ui.spacing.sm,
    borderRadius: ui.radius.md,
    borderWidth: 1,
    borderColor: "#BEEDEA",
    backgroundColor: "#ECFBF9",
    paddingHorizontal: ui.spacing.sm,
    paddingVertical: ui.spacing.sm,
  },
  aiPicksHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: ui.spacing.xs,
  },
  aiPicksTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  aiPicksTitle: {
    fontSize: ui.type.caption,
    color: "#0F766E",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  aiPicksAction: {
    fontSize: ui.type.caption,
    color: ui.colors.primary,
    fontWeight: "800",
  },
  aiPillsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: ui.spacing.xs,
  },
  aiSuggestionPill: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: ui.radius.full,
    borderWidth: 1,
    borderColor: "#A7E7E2",
    backgroundColor: "#D4F5F1",
  },
  aiSuggestionPillText: {
    color: "#0F766E",
    fontSize: ui.type.body,
    fontWeight: "800",
  },
  errorBanner: {
    marginHorizontal: ui.spacing.md,
    marginBottom: ui.spacing.xs,
    backgroundColor: "#FEECEC",
    borderColor: "#F8B4B4",
    borderWidth: 1,
    borderRadius: ui.radius.md,
    paddingHorizontal: ui.spacing.sm,
    paddingVertical: ui.spacing.xs,
  },
  errorBannerText: {
    color: "#B42318",
    fontSize: ui.type.caption,
    fontWeight: "700",
  },
  scrollContent: {
    paddingBottom: ui.spacing.md,
  },
  promptSection: {
    marginHorizontal: ui.spacing.md,
    marginBottom: ui.spacing.sm,
    padding: 14,
    borderRadius: ui.radius.lg,
    borderWidth: 1,
    borderColor: "#CDEEEE",
    backgroundColor: ui.colors.surface,
  },
  promptHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  promptTitle: {
    fontSize: 19,
    fontWeight: "900",
    color: ui.colors.text,
  },
  promptSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  promptToggleButton: {
    borderRadius: ui.radius.full,
    borderWidth: 1,
    borderColor: "#BEEDEA",
    backgroundColor: "#ECFBF9",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  promptToggleText: {
    fontSize: 12,
    color: "#0F766E",
    fontWeight: "800",
  },
  promptGrid: {
    gap: 9,
  },
  promptChip: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#BAEDE9",
    backgroundColor: "#ECFAF8",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  promptChipText: {
    color: ui.colors.text,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "800",
    flex: 1,
    paddingRight: 8,
  },
  tagRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  tagChip: {
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: ui.radius.full,
    backgroundColor: "#D9F4F1",
    borderWidth: 1,
    borderColor: "#BEEDEA",
  },
  tagText: {
    color: "#0F766E",
    fontSize: ui.type.caption,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  restaurantCard: {
    paddingHorizontal: ui.spacing.md,
  },
  detailsContainer: {
    backgroundColor: ui.colors.surface,
    borderRadius: ui.radius.lg,
    padding: ui.spacing.md,
    borderWidth: 1,
    borderColor: ui.colors.border,
    gap: ui.spacing.sm,
    ...ui.shadow.card,
  },
  heroRow: {
    flexDirection: "row",
    gap: 12,
  },
  logo: {
    width: 84,
    height: 84,
    borderRadius: ui.radius.md,
    resizeMode: "cover",
    backgroundColor: "#F3F4F6",
  },
  logoPlaceholder: {
    width: 84,
    height: 84,
    borderRadius: ui.radius.md,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  heroInfo: {
    flex: 1,
    gap: 5,
  },
  restaurantName: {
    fontSize: ui.type.h1,
    fontWeight: "900",
    color: ui.colors.text,
    marginBottom: 2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
  },
  infoIcon: {
    marginTop: 1,
  },
  infoText: {
    flex: 1,
    fontSize: ui.type.body,
    lineHeight: 19,
    color: ui.colors.text,
    fontWeight: "700",
  },
  linkText: {
    flex: 1,
    fontSize: ui.type.body,
    lineHeight: 19,
    color: ui.colors.primary,
    fontWeight: "700",
  },
  restaurantDescription: {
    fontSize: ui.type.body,
    lineHeight: 21,
    color: ui.colors.textMuted,
    fontWeight: "500",
    marginTop: 4,
  },
  quickActions: {
    marginTop: 4,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  menuList: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: ui.colors.text,
  },
  chevronIcon: {
    marginTop: 0,
  },
  mapWrap: {
    marginTop: 8,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#F8FAFC",
  },
  mapFallbackWrap: {
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: ui.spacing.sm,
  },
  mapFallbackText: {
    fontSize: ui.type.caption,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  menuSection: {
    marginTop: ui.spacing.sm,
    marginHorizontal: ui.spacing.md,
    marginBottom: ui.spacing.md,
    paddingTop: ui.spacing.sm,
    borderRadius: ui.radius.md,
    borderTopWidth: 1,
    borderTopColor: ui.colors.border,
  },
  menuSectionHeader: {
    marginBottom: ui.spacing.sm,
  },
  menuSectionTitle: {
    fontSize: ui.type.h2,
    fontWeight: "900",
    color: ui.colors.text,
  },
  menuSectionHint: {
    marginTop: 2,
    fontSize: ui.type.caption,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  menuBlock: {
    marginBottom: ui.spacing.sm,
    borderWidth: 1,
    borderColor: ui.colors.border,
    borderRadius: ui.radius.md,
    overflow: "hidden",
  },
  menuBlockHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: ui.spacing.sm,
    paddingVertical: ui.spacing.sm,
    backgroundColor: "#F8FAFC",
  },
  menuBlockTitle: {
    color: ui.colors.text,
    fontSize: ui.type.body,
    fontWeight: "800",
  },
  menuItemCard: {
    paddingHorizontal: ui.spacing.sm,
    paddingVertical: ui.spacing.xs,
    borderTopWidth: 1,
    borderTopColor: ui.colors.border,
    backgroundColor: ui.colors.surface,
  },
  menuItemTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  menuItemName: {
    flex: 1,
    paddingRight: ui.spacing.xs,
    fontSize: ui.type.body,
    fontWeight: "700",
    color: ui.colors.text,
  },
  menuItemPrice: {
    fontSize: ui.type.body,
    fontWeight: "800",
    color: ui.colors.primary,
  },
  menuItemDesc: {
    marginTop: 4,
    fontSize: ui.type.caption,
    lineHeight: 18,
    color: ui.colors.textMuted,
  },
  emptyMenuWrap: {
    borderWidth: 1,
    borderColor: ui.colors.border,
    borderRadius: ui.radius.md,
    padding: ui.spacing.md,
    backgroundColor: "#F8FAFC",
  },
  emptyMenuText: {
    fontSize: ui.type.body,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  emptySearchWrap: {
    borderWidth: 1,
    borderColor: ui.colors.border,
    borderRadius: ui.radius.md,
    padding: ui.spacing.md,
    backgroundColor: "#F8FAFC",
  },
  emptySearchTitle: {
    fontSize: ui.type.h2,
    fontWeight: "900",
    color: ui.colors.text,
  },
  emptySearchText: {
    marginTop: 4,
    fontSize: ui.type.body,
    lineHeight: 20,
    color: ui.colors.textMuted,
    fontWeight: "600",
  },
  emptySearchButton: {
    marginTop: 10,
    alignSelf: "flex-start",
    borderRadius: ui.radius.full,
    borderWidth: 1,
    borderColor: "#BEEDEA",
    backgroundColor: "#ECFBF9",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  emptySearchButtonText: {
    color: "#0F766E",
    fontSize: ui.type.caption,
    fontWeight: "800",
  },
  emptySearchTags: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  emptySearchRecoveryWrap: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: ui.colors.border,
  },
  emptySearchRecoveryTitle: {
    fontSize: ui.type.caption,
    color: ui.colors.textMuted,
    fontWeight: "700",
  },
});

export default foodMenuStyles;
